#!/usr/bin/env python3

from sys import exit
from lib.application import Application
from lib.window import Window


if __name__ == "__main__":
    app = Application()
    window = Window()
    window.show()
    exit(app.exec())
